version: '3.9'

services:
  de-pg-cr-af:
    image: cr.yandex/crp1r8pht0n0gl25aug1/de-pg-cr-af:latest
    ports:
      - 3000:3000
      - 3002:3002
      - 15432:5432
    volumes:
      - s5t4postgresql:/var/lib/postgresql
      - ${AIRFLOW_DAGS_DIR:-./src/dags}:/lessons/dags
    restart: unless-stopped


volumes:
  s5t4postgresql:

